# Generated by Django 3.1.1 on 2020-11-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('state_city', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('mob1', models.CharField(max_length=100, null=True)),
                ('mob2', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, default='Not Done', max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('img1', models.FileField(null=True, upload_to='')),
                ('img2', models.FileField(null=True, upload_to='')),
                ('img3', models.FileField(null=True, upload_to='')),
                ('des', models.TextField(null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('img', models.FileField(null=True, upload_to='')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.subcategory'),
        ),
        migrations.CreateModel(
            name='order_product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out for Delivery', 'Out for Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True)),
                ('order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.order_product')),
                ('pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
