# Generated by Django 3.1.1 on 2020-11-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0002_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='word',
            new_name='m',
        ),
        migrations.AddField(
            model_name='new',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
        migrations.AddField(
            model_name='new',
            name='u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
