# Generated by Django 3.1.1 on 2020-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20201112_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='d',
            field=models.DateField(blank=True, null=True),
        ),
    ]
